# Application name
spring.application.name=backend

# PostgreSQL database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/guildboard
spring.datasource.username=postgres
spring.datasource.password=SOnia1982@@@

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=validate

# Show SQL queries in the console
spring.jpa.show-sql=true

# Format SQL queries
spring.jpa.properties.hibernate.format_sql=true